CREATE DATABASE IF NOT EXISTS SHM_BOOKS;

USE SHM_BOOKS;

CREATE TABLE IG_USERS
(
	US_ID INT AUTO_INCREMENT,
    US_EMAIL VARCHAR(500) NOT NULL UNIQUE,
    US_PASS VARCHAR(500) NOT NULL,
    CONSTRAINT US_PK PRIMARY KEY (US_ID) 
);

CREATE TABLE IG_BOOKS 
(
	BK_ID INT AUTO_INCREMENT,
    BK_TITLE VARCHAR(300) NOT NULL,
    BK_AUTHOR VARCHAR(500) NOT NULL,
	BK_PUBLISHER VARCHAR(500) NOT NULL,
    BK_GENRE VARCHAR(45) NOT NULL,
    BK_LINK VARCHAR(1000) NOT NULL,
    BK_DESCRIPTION VARCHAR(500) NOT NULL,
    CONSTRAINT BK_PK PRIMARY KEY (BK_ID)
);

CREATE TABLE US_HAS_BK
(
	UHB_BK INT,
    UHB_US INT,
    CONSTRAINT UHB_FK_BK FOREIGN KEY (UHB_BK) REFERENCES IG_BOOKS (BK_ID),
    CONSTRAINT UHB_FK_US FOREIGN KEY (UHB_US) REFERENCES IG_USERS (US_ID)
);